### ISSUE TITLE
Question about the pre-processed AIDA data

### ISSUE THREAD

**Issue by laituan245** [nicola-decao/efficient-autoregressive-EL#1]
Hi.

Thank you for open-sourcing your code. This is a great EL system.

I have one question about your pre-processed AIDA data. I guess in each example, the field `anchors` contains the list of the entity mentions? And for each entity mention, you have the word start index, word end index, and the Wikipedia name?

If so, are there any misalignment issues in the preprocessed data? Like in the first example in the training set ("EU rejects German ..."), there is `(12,14,Brussels)`, however, the tokens from 12 to 14 is `BRUSSELS 1996-08-22 The`. Is this a misalignment or did I misunderstand something?

Thank you.

**Comment by nicola-decao** [comment]
Hi! The tokenization is correct. I do not use word tokenization but BPE tokenization. The file is preprocessed to be used by the model directly that is using the standard GPT2 tokenizer (same as Longformer, RoBERTa, BART and many other models). You can see here that `BRUSSELS` is actually 3 BPEs so the alignment `(12,14,Brussels)` makes sense.

```python
>>> from transformers import GPT2Tokenizer
>>> GPT2Tokenizer.from_pretrained("gpt2-large").tokenize("BRUSSELS")

['BR', 'USS', 'ELS']
```

**Comment by laituan245** [comment]
That makes sense. Thank you.
