### ISSUE TITLE
Providing candidates

### ISSUE THREAD

**Issue by hertelm** [nicola-decao/efficient-autoregressive-EL#6]
I wonder how to provide candidates.

The [example notebook](https://github.com/nicola-decao/efficient-autoregressive-EL/blob/master/notebooks/Test.ipynb) doesn't show that functionality. Therefore "Phil Simmons" gets wrongly linked to [Philip Walton](https://en.wikipedia.org/wiki/Philip_Walton). However, in the file *aida_val_dataset.jsonl* the only candidate for "Phil Simmons" is "Phil Simmons".

Does the model make use of the pre-computed candidate sets when *trainer.test()* is run?

**Comment by nicola-decao** [comment]
When using `trainer.test()` by default, the model uses candidates (see here https://github.com/nicola-decao/efficient-autoregressive-EL/blob/3ad361845995d2527b14e863c478ef152b21f4e5/src/model/efficient_el.py#L376)
