### ISSUE TITLE
Start and end position indexes in  dataset

### ISSUE THREAD

**Issue by hezongfeng** [nicola-decao/efficient-autoregressive-EL#7]
Hello! Honour to read your code! 
    How do you generate the start and end position indexes in all datasets? I found that the start and end position indexes do not correctly locate the mention. 
    Looking forward to your reply!

`
    {"id": "947testa 947testa", "input": "CRICKET - LEICESTERSHIRE TAKE OVER AT TOP AFTER INNINGS VICTORY . LONDON 1996-08-30 West Indian all-rounder Phil Simmons took four for 38 on Friday as Leicestershire beat Somerset by an innings and 39 runs in two days to take over at the head of the county championship . Their stay on top , though , may be short-lived as title rivals Essex , Derbyshire and Surrey all closed in on victory while Kent made up for lost time in their rain-affected match against Nottinghamshire . After bowling Somerset out for 83 on the opening morning at Grace Road , Leicestershire extended their first innings by 94 runs before being bowled out for 296 with England discard Andy Caddick taking three for 83 . Trailing by 213 , Somerset got a solid start to their second innings before Simmons stepped in to bundle them out for 174 . Essex , however , look certain to regain their top spot after Nasser Hussain and Peter Such gave them a firm grip on their match against Yorkshire at Headingley . Hussain , considered surplus to England 's one-day requirements , struck 158 , his first championship century of the season , as Essex reached 372 and took a first innings lead of 82 . By the close Yorkshire had turned that into a 37-run advantage but off-spinner Such had scuttled their hopes , taking four for 24 in 48 balls and leaving them hanging on 119 for five and praying for rain . At the Oval , Surrey captain Chris Lewis , another man dumped by England , continued to silence his critics as he followed his four for 45 on Thursday with 80 not out on Friday in the match against Warwickshire . He was well backed by England hopeful Mark Butcher who made 70 as Surrey closed on 429 for seven , a lead of 234 . Derbyshire kept up the hunt for their first championship title since 1936 by reducing Worcestershire to 133 for five in their second innings , still 100 runs away from avoiding an innings defeat . Australian Tom Moody took six for 82 but Chris Adams , 123 , and Tim O'Gorman , 109 , took Derbyshire to 471 and a first innings lead of 233 . After the frustration of seeing the opening day of their match badly affected by the weather , Kent stepped up a gear to dismiss Nottinghamshire for 214 . They were held up by a gritty 84 from Paul Johnson but ex-England fast bowler Martin McCague took four for 55 . By stumps Kent had reached 108 for three .", "anchors": [[5, 10, "Leicestershire County Cricket Club"], [24, 25, "London"], [31, 32, "West Indies cricket team"], [36, 37, "Phil Simmons"], [45, 48, "Leicestershire County Cricket Club"], [50, 50, "Somerset County Cricket Club"], [86, 86, "Essex County Cricket Club"], [88, 90, "Derbyshire County Cricket Club"], [92, 92, "Surrey County Cricket Club"], [99, 99, "Kent County Cricket Club"], [112, 113, "Nottinghamshire County Cricket Club"], [117, 117, "Somerset County Cricket Club"], [126, 127, "Grace Road"], [129, 132, "Leicestershire County Cricket Club"], [148, 148, "England cricket team"], [150, 153, "Andrew Caddick"], [164, 164, "Somerset County Cricket Club"], [174, 174, "Phil Simmons"], [184, 184, "Essex County Cricket Club"], [196, 198, "Nasser Hussain"], [200, 201, "Peter Such"], [211, 211, "Yorkshire County Cricket Club"], [213, 215, "Headingley"], [217, 217, "Nasser Hussain"], [222, 222, "England cricket team"], [242, 242, "Essex County Cricket Club"], [257, 257, "Yorkshire County Cricket Club"], [272, 272, "Peter Such"], [302, 302, "The Oval"], [304, 304, "Surrey County Cricket Club"], [306, 307, "Chris Lewis (cricketer)"], [313, 313, "England cricket team"], [339, 342, "Warwickshire County Cricket Club"], [349, 349, "England cricket team"], [351, 352, "Mark Butcher"], [357, 357, "Surrey County Cricket Club"], [369, 371, "Derbyshire County Cricket Club"], [385, 388, "Worcestershire County Cricket Club"], [408, 408, "Australia"], [409, 410, "Tom Moody"], [416, 417, "Chris Adams (cricketer)"], [431, 433, "Derbyshire County Cricket Club"], [462, 462, "Kent County Cricket Club"], [469, 470, "Nottinghamshire County Cricket Club"], [483, 484, "Paul Johnson (cricketer)"], [492, 494, "Martin McCague"], [503, 503, "Kent County Cricket Club"}
`

**Comment by nicola-decao** [comment]
What do you mean by 
> I found that the start and end position indexes do not correctly locate the mention. 
They looks correct to me.

**Comment by hezongfeng** [comment]
Such as the above anchors [5, 10, "Leicestershire County Cricket Club"] and [24, 25, "London"]， How to get [5,10] and [24,25]？

**Comment by hezongfeng** [comment]
Does [5,10] represent an anchor that starts with the 5th word and ends with the 10th word in the input sentence? Can you give me a brief explanation?  I'm very confused about this.  Thank you very much.

**Comment by nicola-decao** [comment]
`[5, 10, "Leicestershire County Cricket Club"]` indicates that from the 5th and 10th tokens (tokenized with `AutoTokenizer.from_pretrained("allenai/longformer-base-4096")`) will contain a mention that needs to be linked to "Leicestershire County Cricket Club". Same for the London one
