### ISSUE TITLE
Very different results from GENRE

### ISSUE THREAD

**Issue by Valdegg** [nicola-decao/efficient-autoregressive-EL#8]
I want to use end2end EL in production, so it needs to be fast. 
GENRE is accurate enough for use, but not fast enough, so I've been trying this model instead (assuming that it's on par with GENRE in accuracy).

I tried a few sentences: 
"I visited Bologne while I was in Italy",
'In a televised meeting across a small table from his defence minister, Vladimir Putin ordered his forces to hold back from storming the Azovstal steel plant.', 
"While in Memphis he did not go to the blues clubs that he would have visited if he was back home, instead he visited the hall of Ramses II"

and GENRE linked most of them correctly, while the efficient model just failed completely at almost all the names, predicting "Breda" for "Bologne", "Miami" to "Memphis" and "Rolf Ekéus" to "Ramses II".

Is the model in https://mega.nz/folder/l4RhnIxL#_oYvidq2qyDIw1sT-KeMQA   untrained?

Any idea why the model is linking random entities that start with the same letter as the name in the text, instead of an entity with the same or similar name?

**Comment by nicola-decao** [comment]
Hi, the uploaded model was trained on AIDA-CoNLL (Hoffart et al., 2011) and not on Wikipedia so it is expected not to work on general entities. AIDA-CoNLL is also small (ie, less than 1k documents and less than 20k entities). I did and do not have the computational resources to train it on a full Wikipedia dump sorry.
